### ISSUE TITLE
Find extension by OID/type

### ISSUE THREAD

**Issue by cereblanco** [PeculiarVentures/x509#32]
Hello! Thank you for this library. 🙇🏼‍♀️ 

Do we have support for finding a certificate extension given a `oid` (in the case of Extension class, that would be type)?
I would like to create a util for it if it does not exist yet. Thank you

**Comment by rmhrisk** [comment]
Not without an enumeration of extensions

**Comment by microshine** [comment]
https://peculiarventures.github.io/x509/classes/X509Certificate.html

The current API implements `getExtension` and `getExtensions` methods. These methods allow getting `Extension` by OID or Extension class

```js
// get by OID
cert.getExtension("2.5.29.15");

// get by class
cert.getExtensions(x509.KeyUsagesExtension)
```

see [tests](https://github.com/PeculiarVentures/x509/blob/master/test/crypto.ts#L367-L389)

**Comment by cereblanco** [comment]
Exactly what i needed. Thank you! 

Closing this issue now.
