### ISSUE TITLE
Library does not work in Safari web browser (desktop and iOS)

### ISSUE THREAD

**Issue by WorldThirteen** [PeculiarVentures/x509#4]
Safari (desktop and iOS) does not support a negative look behind in the regular expression ([caniuse](https://caniuse.com/?search=lookbehind)). While such a feature is used in the next regular expression: https://github.com/PeculiarVentures/x509/blob/master/src/name.ts#L162.
UPD: one more https://github.com/PeculiarVentures/x509/blob/master/src/name.ts#L186.

Safari throws a runtime error: `SyntaxError: Invalid regular expression: invalid group specifier name`.

Steps to reproduce:
1. Create HTML with `<script src="https://unpkg.com/@peculiar/x509"></script>`
2. Open it in the Safari browser (Version 14.0.2 (16610.3.7.1.9).
3. See an error in the console, x509 object doesn't add to the global scope.

**Comment by microshine** [comment]
The problem is with Lookbehind expression

![image](https://user-images.githubusercontent.com/7333669/104391477-fae52d00-5550-11eb-8f1f-d90b5ffd4737.png)

**Comment by rmhrisk** [comment]
http://blog.stevenlevithan.com/archives/mimic-lookbehind-javascript/comment-page-1

**Comment by microshine** [comment]
I published the new version `1.0.10`

[Try it](https://codesandbox.io/s/generate-csr-0qhed?file=/index.html)
