### ISSUE TITLE
Types missing from v1.9.0

### ISSUE THREAD

**Issue by jacobwgillespie** [PeculiarVentures/x509#50]
Hey! The types are broken in the new 1.9.0, because now that `tests` exists, TypeScript is generating the types at `build/types/src/*` instead of `build/types/*`:

https://unpkg.com/browse/@peculiar/x509@1.9.0/build/types/

**Comment by microshine** [comment]
`@peculiar/x509@1.9.2` has been published. Please try it.

**Comment by jacobwgillespie** [comment]
It works! 🎉 Thanks for the fast turnaround
