### ISSUE TITLE
createSelfSigned method causes out of memory crash in Node 16.x

### ISSUE THREAD

**Issue by TJKoury** [PeculiarVentures/x509#7]
Values taken from browser example:

```
 const algorithm = {
        name: "RSASSA-PKCS1-v1_5",
        hash: "SHA-256",
        modulusLength: 2048,
        publicExponent: new Uint8Array([1, 0, 1])
    }
 
 const caKeys = await generateKey(algorithm, true, ["sign", "verify"]);

 const caCert = await x509.X509CertificateGenerator.createSelfSigned({
        serialNumber: "01",
        subject: "CN=Test certificate, E=some@email.net",
        notBefore: new Date("2020/01/01"),
        notAfter: new Date("2022/01/02"),
        signingAlgorithm: {
            "name": "RSASSA-PKCS1-v1_5",
            "hash": "SHA-256",
            "modulusLength": 2048,
            "publicExponent": {
                "0": 1,
                "1": 0,
                "2": 1
            }
        },
        keys: caKeys,
        extensions: [
            {
                "rawData": {},
                "type": "2.5.29.19",
                "critical": true,
                "value": {},
                "ca": false
            },
            {
                "rawData": {},
                "type": "2.5.29.15",
                "critical": true,
                "value": {},
                "usages": 9
            },
            {
                "rawData": {},
                "type": "2.5.29.14",
                "critical": false,
                "value": {},
                "keyId": "84cb7d152ef9ebb1eef48a300b9e4b8470590b4a"
            }
        ]
    });
```

**Comment by microshine** [comment]
It's strange. Just added Node v16 to CI and all tests are passed

https://github.com/PeculiarVentures/x509/runs/2642497851?check_suite_focus=true#step:7:65

**Comment by microshine** [comment]
Which crypto provider do you use?

**Comment by microshine** [comment]
Strange arguments are in your example

Try
```js
const cert = await x509.X509CertificateGenerator.createSelfSigned({
  serialNumber: "01",
  name: "CN=Test",
  notBefore: new Date("2020/01/01"),
  notAfter: new Date("2020/01/02"),
  signingAlgorithm: {
    name: "RSASSA-PKCS1-v1_5"
  },
  keys: keys,
  extensions: [
    new x509.BasicConstraintsExtension(true, 2, true),
    new x509.ExtendedKeyUsageExtension(["1.2.3.4.5.6.7", "2.3.4.5.6.7.8"], true),
    new x509.KeyUsagesExtension(x509.KeyUsageFlags.keyCertSign | x509.KeyUsageFlags.cRLSign, true),
    await x509.SubjectKeyIdentifierExtension.create(keys.publicKey),
  ]
});
```

**Comment by TJKoury** [comment]
That works.  Throwing an error if it is an invalid extension would be preferable to an out of memory crash.

**Comment by rmhrisk** [comment]
> That works. Throwing an error if it is an invalid extension would be preferable to an out of memory crash.

Which crypto provider are you using?

**Comment by TJKoury** [comment]
Tried it with native, liner, and peculiar webcrypto.

**Comment by rmhrisk** [comment]
Sound environmental given it did not reproduce. @microshine do I understand correctly it didn’t reproduce?

**Comment by microshine** [comment]
The extension value which was used for example doesn't match to `@peculiar/x509` requirements. It must be the instance of the `Extension` class. See https://peculiarventures.github.io/x509/interfaces/x509certificatecreateselfsignedparams.html#extensions

### Wrong value
```js
{
  "rawData": {},
  "type": "2.5.29.19",
  "critical": true,
  "value": {},
  "ca": false
}
```

### Correct value
```
new x509.BasicConstraintsExtension(false, undefined, true)
```

> That works. Throwing an error if it is an invalid extension would be preferable to an out of memory crash.

`@peculiar/x509` uses type declarations which allows validating types during development. See my screenshot. It allows minimizing sourcecode and skip `if..then..throw` wrong types validation

![image](https://user-images.githubusercontent.com/7333669/119275071-b0b93a00-bc1b-11eb-8cb6-af31541f478c.png)

**Comment by TJKoury** [comment]
It was a test (incorrect) deserialization, I’ll upload a demo repo.

**Comment by TJKoury** [comment]
The issue with .ts typing in my use case is that I’m trying to create flatbuffer schemas to serialize instances.  Yes, I know the whole point of using x509 is serialization, but I have some meta programming tools (like [this](https://spacedatastandards.org)) that share fields.  I would like to be able to serialize the data without having to use ASN.1 et al for the data structure, or have to store the entire certificate / key as a blob.

**Comment by TJKoury** [comment]
I can get this to consistently crash on Node 15.x && 16.x on POPOS (Debian / Ubuntu), but not on OSX or Windows.  Seems to be environmental, closing for now.
