### ISSUE TITLE
err: Data does not match to ECParameters ASN1 schema. Wrong values for Choice type

### ISSUE THREAD

**Issue by li0ard** [PeculiarVentures/x509#88]
Hi, i got error `Data does not match to ECParameters ASN1 schema. Wrong values for Choice type` when call X509Certificate constructor, but certificate is valid.
Code:
```ts
new X509Certificate(
    await Bun.file("./sod.pem").bytes()
)
```
![image](https://github.com/user-attachments/assets/c25f44a8-a52b-421b-9fdb-6375f22fa397)
Certificate:
[sod.zip](https://github.com/user-attachments/files/17002458/sod.zip)

**Comment by microshine** [comment]
The latest version of `@peculiar/asn1-ecc` fixes this problem. `@peculiar/x509` parses the certificate and returns `cert.publicKey.alofirthm` like

```js
{
  name: '1.2.840.10045.2.1',
  parameters: Uint8Array(250) [
     48, 129, 247,   2,   1,   1,  48,  44,   6,   7,  42, 134,
     72, 206,  61,   1,   1,   2,  33,   0, 255, 255, 255, 255,
      0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255,  48,  91,   4,  32, 255, 255, 255, 255,
      0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 252,   4,  32,  90, 198,  53, 216, 170,  58,
    147, 231, 179, 235,
    ... 150 more items
  ]
}
```

Going to publish the new version of `@peculiar/x509` with updated dependencies in the nearest time

**Comment by microshine** [comment]
`@peculiar/x509@1.12.2` ha been published
